### PR TITLE
Update nan dependency from 0.8 to 1.6 (so node 12 / iojs)

### PR DESCRIPTION
**Pull request by lmeyerov**
AFAICT, works on node 10.26, iojs, and node 12. 

Unclear how to test, so should check.

### CODE REVIEW

**Comment by jhludwig** [comment]
Imeryerov, the node-webgl examples work for me, but when i try to use three.js as modified by kabbi for node use (https://github.com/kabbi/three.js), i get the following failure on iojs 1.6.2 or node v0.12.0.  the whole stack does work ok on node 0.10.25.

this error is being generated out of webgl.cc. line ~372.  in walking thru the execution using node-debugger and gdb, it would appear that the javascript array does have the requisite 16 elements, but webgl.cc is not seeing that size array.  i am still digging into...any thoughts?

```
/home/john/ws/var/release/install/bin/hostjs/node_modules/node-webgl/lib/webgl.js:1004
  return _uniformMatrix4fv(location ? location._ : 0, transpose, value);
         ^
Error: Not enough data for UniformMatrix4fv
    at Error (native)
    at Object.uniformMatrix4fv (/home/john/ws/var/release/install/bin/hostjs/node_modules/node-webgl/lib/webgl.js:1004:10)
    at loadUniformsGeneric (/home/john/ws/var/release/install/bin/hostjs/node_modules/three/three.js:22802:10)
    at setProgram (/home/john/ws/var/release/install/bin/hostjs/node_modules/three/three.js:22248:4)
    at renderBufferDirect (/home/john/ws/var/release/install/bin/hostjs/node_modules/three/three.js:20158:17)
    at renderObjects (/home/john/ws/var/release/install/bin/hostjs/node_modules/three/three.js:21197:11)
    at render (/home/john/ws/var/release/install/bin/hostjs/node_modules/three/three.js:21070:4)
    at render (/home/john/ws/var/release/install/bin/hostjs/example3/example-cube.js:29:11)
    at Object.<anonymous> (/home/john/ws/var/release/install/bin/hostjs/example3/example-cube.js:32:1)
```

**Comment by lmeyerov** [comment]
Hum, not sure, I did this to enable node-webcl to compile. We deactivated our gl interop pipeline for now so haven't been using, but may bring back in a couple months. 

Maybe the Array::New -> NanNew<Array> refactoring is wrong?

**Comment by mikeseven** [comment]
humm, this would seem a bug in passing the right number of values to uniformMatrix4fv.
I’ll try to find some time to check node-webgl/glfw to latest version of nodejs and iojs but I’m really overwhelmed currently.

— mike

**Comment by jhludwig** [comment]
thanks for any help.  i will continue to dig in.  if i can help you in anyway, let me know.

**Pull request merged**
